# Generated by Django 3.1.2 on 2020-11-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
        ('movie', '0002_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Actors',
            field=models.ManyToManyField(blank=True, to='actor.Actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Metascore',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='movie',
            name='Poster_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Ratings',
            field=models.ManyToManyField(blank=True, to='movie.Rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbRating',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbVotes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
