# Generated by Django 3.1.2 on 2020-11-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201116_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='BoxOffice',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='movie',
            name='DVD',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='movie',
            name='Production',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='Type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='Website',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='totalSeasons',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
