# Generated by Django 3.1.2 on 2020-11-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201116_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Relesed',
            new_name='Released',
        ),
    ]
